### ISSUE TITLE
Regarding 500 error while uploading the Attachment

### ISSUE THREAD

**Issue by knowband-plugins** [PrestaShop/addons-seller-api#2]
Hi,

In the send message API, We are getting 500 error while uploading the file (Sending the attachment as well).

We are using these API from around 2 years & it was working fine till 8-10 days back but now API is throwing 500 error.  Kindly note that "Send message" API without attachment is working fine.

CURL Info response is below.

  | HTTP/1.1 500 Internal Server Error
  | Server: nginx
  | Date: Wed, 17 Oct 2018 09:39:06 GMT
  | Content-Type: text/html; charset=utf-8
  | Transfer-Encoding: chunked
  | X-XSS-Protection: 1; mode=block
  | X-Content-Type-Options: nosniff
  | Cache-Control: no-cache
  | Access-Control-Allow-Origin: *
  | X-UA-Compatible: IE=Edge,chrome=1

**Comment by shubhwebkul** [comment]
I am having the same issue while sending a request with attachment. Is there any solution yet .?

**Comment by shubhwebkul** [comment]
Is there any update.?

**Comment by MrBaiame** [comment]
Hello and sorry about the huge delay. Could you display the variables you are sending please ?

**Comment by shubhwebkul** [comment]
Same issue as mentioned in #3

**Comment by shubhwebkul** [comment]
Hello there,
Is there any update @MrBaiame .?

**Comment by MrBaiame** [comment]
Hello @shubhwebkul  ,

Sorry about the huge delay, we've been very busy. The issue should be fixed now. 
Feel free to test and tell us if anything is not working properly.

Bests
