### ISSUE TITLE
sending attachment to the message send post api not working

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/addons-seller-api#3]
- end URL: https://api.addons.prestashop.com/request/seller/threads/{id_thread}/messages/add
- post data: $post here, https://github.com/PrestaShop/addons-seller-api/blob/master/SellerApi.php#L73
is like this,
```
Array
(
    [api_key] => my_key
    [message] => 'data with attachment'
    [attachment] => CURLFile Object
        (
            [name] => /tmp/phpudvSqe
            [mime] => 
            [postname] => 
        )
)
```
we got this error in response:
"{"errors":{"code":"0000","label":"Wrong Parameters - Wrong file extension"}}"
{"errors":{"code":"0000","label":"Wrong Parameters - Wrong file extension"}}

I have provided mime and postman also but still this error.

Other, if I send directly array not CURLFile like this
```
Array
(
    [api_key] => my_key
    [message] => 'data with attachment'
    [attachment] => Array
        (
            [name] => demo.png
            [type] => image/png
            [tmp_name] => /tmp/phpHXsq7p
            [error] => 0
            [size] => 1009
        )
)
```
I got the success message, and message is sent also. But I can not see the attachment on the seller addon support ticket page , see this screenshot for this case,
![download (12)](https://user-images.githubusercontent.com/19220745/62035749-11d57980-b20e-11e9-9fff-e30e86deb6d4.png)

 Please check this issue.

Thanks,

**Comment by dheerajwebkul** [comment]
I think this is the right post parameter should be this:
```
Array
(
    [api_key] => my_key
    [message] => new attachment
    [attachment] => CURLFile Object
        (
            [name] => /tmp/phpWd3wWO
            [mime] => image/png
            [postname] => demo.png
        )
)
```
which is giving a new type of error, its html response. check screenshot,

![download (14)](https://user-images.githubusercontent.com/19220745/62037647-cde47380-b211-11e9-9455-2623190623a4.png)

![AwesomeScreenshot-tetrsetet-2019-07-29-15-07-70](https://user-images.githubusercontent.com/19220745/62037856-3c293600-b212-11e9-88a7-cfad9b36d695.png)

**Comment by MrBaiame** [comment]
Hello, 

The type of the attachment should be "array", not CURLFile Object, could you try with sending an array and tell me if you get an error ?

Bests

**Comment by dheerajwebkul** [comment]
@MrBaiame thanks for response,
Is this type of post you say,

```
Array
(
    [api_key] => my_key
    [message] => 'data with attachment'
    [attachment] => Array
        (
            [name] => demo.png
            [type] => image/png
            [tmp_name] => /tmp/phpHXsq7p
            [error] => 0
            [size] => 1009
        )
)
```
?

**Comment by dheerajwebkul** [comment]
@MrBaiame I sent the above and this one also to check,
```
Array
(
    [api_key] => my_key
    [message] => new attachment
    [attachment] => Array
        (
            [name] => /tmp/phpnDM26h
            [mime] => image/png
            [postname] => demo.png
        )
)
```
In both case the message sent with success,
```
{"success":true}
```
But the I can not see attachment link there on website, is this really sent,
![download (15)](https://user-images.githubusercontent.com/19220745/62038710-d9d13500-b213-11e9-982e-ccdf20293855.png)

**Comment by dheerajwebkul** [comment]
Hello @MrBaiame 
Is there any update regarding this issue?

Thanks,

**Comment by dheerajwebkul** [comment]
@MrBaiame 

I am waiting for your response as without this the seller api can not be used.

Thanks,

**Comment by dheerajwebkul** [comment]
I can not find here also, how to deal with attachments in the post api

https://api.addons.prestashop.com/request/seller/threads/{id_thread}/messages/add

API.

**Comment by dheerajwebkul** [comment]
Hello @MrBaiame 

Is there any update regarding this issue?

**Comment by dheerajwebkul** [comment]
Hello @MrBaiame 

We are not getting any update from you.

Can we fix this issue?

without this the api is useless.

Thanks,

**Comment by dheerajwebkul** [comment]
Hello,

No update on this issue.
Looks like prestashop seller api will no longer in support and existance.
This API is depricated now.

Thanks,

**Comment by dheerajwebkul** [comment]
Hello,

any update on this issue?

**Comment by MrBaiame** [comment]
Hello @dheerajwebkul ,

Sorry about the huge delay, we've been very busy. The issue should be fixed now. 
Feel free to test and tell us if anything is not working properly.

Bests
